name: 'docker action'
description: 'does auth, build and push'
author: 'Tradeshift'
inputs:
  build-args:
    required: false
    description: list of build args
  builder:
    required: false
    description: buildx builder to use
  context:
    required: true
    description: docker context
    default: .
  file:
    required: false
    description: path to dockerfile
  labels:
    required: false
    description: list of labels
  password:
    required: false
    description: >
      Password for docker registry detected from the repository.
  push:
    required: false
    description: wether to push or not
    default: true
  repository:
    required: false
    description: >
      The repository where default tags will be pushed. If not specified this
      will default to eu.gcr.io/tradeshift-base/<repo-name>
  tags:
    required: false
    description: list of tags
  username:
    required: false
    description: >
      Username for docker registry detected from the repository.
    default: _json_key
  auth-only:
    required: true
    description: >
      This flag can be used in case only authentication against docker 
      repo is needed
    default: false
outputs:
  builder:
    description: buildx builder name
  image:
    description: full image name including git SHA tag
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
